name: "Ccache for gh actions"
description: "A GitHub Action that speeds up compiling for C/C++ projects using ccache."
author: "Hendrik Muhs<hendrik.muhs@gmail.com>"
inputs:
  key:
    description: "An additional key for the cache"
    required: false
  restore-keys:
    description: "An ordered list of keys to use for restoring the cache if no cache hit occurred for key"
    required: false
  ccache-dir:
    description: "ccache-dir config"
    default: "~/.ccache"
  sccache-dir:
    description: "sccache-dir config"
    default: ""
  max-size:
    description: "Max size of the cache"
    default: "500M"
  verbose:
    description: "Verbosity level: 0 (default), 1 or 2. Ignore for sccache."
    default: 0
  variant:
    description: 'Ccache variant to use. Either "ccache" (the default) or "sccache" (see https://github.com/mozilla/sccache)'
    default: ccache
  install-from-github:
    description: 'install Ccache from Github Releases https://github.com/ccache/ccache/releases/'
    default: 'false'
    required: false
  save:
    description: "If 'false', do not save the cache, only restore."
    default: true
  append-timestamp:
    description: "Append a timestamp to the cache key (default: true)"
    default: true
    required: false
runs:
  using: "node16"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
