.TH UPDATE-CCACHE-SYMLINKS 8 "2010-08-08"
.SH NAME
update-ccache-symlinks \- update symlinks in /usr/lib/ccache
.SH SYNOPSIS
.B update-ccache-symlinks
.SH DESCRIPTION
\fBupdate-ccache-symlinks\fR creates and removes symlinks in
\fI/usr/lib/ccache\fR. See the \fBccache\fR man page for more information.
.P
It is normally not necessary to run \fBupdate-ccache-symlinks\fR by hand as
this is done automatically when compiler packages are removed or
installed.
.SH SEE ALSO
.BR ccache (1)
.SH AUTHOR
This manual page was written by Joel Rosdahl <joel@debian.org> for the
Debian GNU/Linux system.
